//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Combiner.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class LuaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LuaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Combiner.Domain.Resources.LuaResources", typeof(LuaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can_dig.
        /// </summary>
        public static string Ability_CanDig {
            get {
                return ResourceManager.GetString("Ability_CanDig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to herding.
        /// </summary>
        public static string Ability_Herding {
            get {
                return ResourceManager.GetString("Ability_Herding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is_immune.
        /// </summary>
        public static string Ability_IsImmune {
            get {
                return ResourceManager.GetString("Ability_IsImmune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loner.
        /// </summary>
        public static string Ability_Loner {
            get {
                return ResourceManager.GetString("Ability_Loner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overpopulation.
        /// </summary>
        public static string Ability_Overpopulation {
            get {
                return ResourceManager.GetString("Ability_Overpopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack_hunter.
        /// </summary>
        public static string Ability_PackHunter {
            get {
                return ResourceManager.GetString("Ability_PackHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poison_pincers.
        /// </summary>
        public static string Ability_PoisonPincers {
            get {
                return ResourceManager.GetString("Ability_PoisonPincers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regeneration.
        /// </summary>
        public static string Ability_Regeneration {
            get {
                return ResourceManager.GetString("Ability_Regeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to armour-front.
        /// </summary>
        public static string Armour_Front {
            get {
                return ResourceManager.GetString("Armour_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hitpoints-front.
        /// </summary>
        public static string Hitpoints_Front {
            get {
                return ResourceManager.GetString("Hitpoints_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to airspeed_max-wings.
        /// </summary>
        public static string SpeedMax_Airspeed_Wings {
            get {
                return ResourceManager.GetString("SpeedMax_Airspeed_Wings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed_max-back.
        /// </summary>
        public static string SpeedMax_LandSpeed_Back {
            get {
                return ResourceManager.GetString("SpeedMax_LandSpeed_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed_max-front.
        /// </summary>
        public static string SpeedMax_LandSpeed_Front {
            get {
                return ResourceManager.GetString("SpeedMax_LandSpeed_Front", resourceCulture);
            }
        }
    }
}
