//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Combiner.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LuaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LuaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Combiner.Domain.Resources.LuaResources", typeof(LuaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to airspeed_max-wings.
        /// </summary>
        internal static string AirspeedMaxWings {
            get {
                return ResourceManager.GetString("AirspeedMaxWings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to armour-front.
        /// </summary>
        internal static string ArmourFront {
            get {
                return ResourceManager.GetString("ArmourFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can_dig.
        /// </summary>
        internal static string CanDig {
            get {
                return ResourceManager.GetString("CanDig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exp_melee8_damage.
        /// </summary>
        internal static string ExpMelee8Damage {
            get {
                return ResourceManager.GetString("ExpMelee8Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exp_range8_damage.
        /// </summary>
        internal static string ExpRange8Damage {
            get {
                return ResourceManager.GetString("ExpRange8Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to herding.
        /// </summary>
        internal static string Herding {
            get {
                return ResourceManager.GetString("Herding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hitpoints-front.
        /// </summary>
        internal static string HitpointsFront {
            get {
                return ResourceManager.GetString("HitpointsFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is_immune.
        /// </summary>
        internal static string IsImmune {
            get {
                return ResourceManager.GetString("IsImmune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loner.
        /// </summary>
        internal static string Loner {
            get {
                return ResourceManager.GetString("Loner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to melee2_dmgtype.
        /// </summary>
        internal static string Melee2DamageType {
            get {
                return ResourceManager.GetString("Melee2DamageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to melee8_dmgtype.
        /// </summary>
        internal static string Melee8DamageType {
            get {
                return ResourceManager.GetString("Melee8DamageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overpopulation.
        /// </summary>
        internal static string Overpopulation {
            get {
                return ResourceManager.GetString("Overpopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack_hunter.
        /// </summary>
        internal static string PackHunter {
            get {
                return ResourceManager.GetString("PackHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poison_pincers.
        /// </summary>
        internal static string PoisonPincers {
            get {
                return ResourceManager.GetString("PoisonPincers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range2_damage.
        /// </summary>
        internal static string Range2Damage {
            get {
                return ResourceManager.GetString("Range2Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range2_dmgtype.
        /// </summary>
        internal static string Range2DamageType {
            get {
                return ResourceManager.GetString("Range2DamageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range2_max.
        /// </summary>
        internal static string Range2Max {
            get {
                return ResourceManager.GetString("Range2Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range2_special.
        /// </summary>
        internal static string Range2Special {
            get {
                return ResourceManager.GetString("Range2Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range8_damage.
        /// </summary>
        internal static string Range8Damage {
            get {
                return ResourceManager.GetString("Range8Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range8_dmgtype.
        /// </summary>
        internal static string Range8DamageType {
            get {
                return ResourceManager.GetString("Range8DamageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range8_max.
        /// </summary>
        internal static string Range8Max {
            get {
                return ResourceManager.GetString("Range8Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range8_special.
        /// </summary>
        internal static string Range8Special {
            get {
                return ResourceManager.GetString("Range8Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regeneration.
        /// </summary>
        internal static string Regeneration {
            get {
                return ResourceManager.GetString("Regeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed_max-back.
        /// </summary>
        internal static string SpeedMaxBack {
            get {
                return ResourceManager.GetString("SpeedMaxBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed_max-front.
        /// </summary>
        internal static string SpeedMaxFront {
            get {
                return ResourceManager.GetString("SpeedMaxFront", resourceCulture);
            }
        }
    }
}
